[phases.setup]
nixPkgs = ['nodejs_18', 'python3', 'python3Packages.pip']

[phases.build]
cmds = ['cd backend/voice-assistant && npm install && pip3 install -r requirements.txt']

[start]
cmd = 'cd backend/voice-assistant && python3 stt_server.py & npm start'